### ISSUE TITLE
LeetCode Medium Problems

### ISSUE THREAD

**Issue by MauryaD** [Amish1902/tshirt_ka_chakkar-baabu-bhaiya-#24]
Hi Amish,
Can we have this as new issue please?
A directory where people can submit their understanding and approaches to LeetCode problems(mainly medium in one folder).

**Comment by MauryaD** [comment]
If you agree, please let me know. I can start working on it.
Cheers!! 👍

**Comment by Amish1902** [comment]
Yeah, btw I am maintaining a leetcode repo also but I have not added
hacktoberfest tags to it. So, should I add Hacktoberfest tags to that repo
or create a new fresh repo?😄

**Comment by MauryaD** [comment]
If you're already having the repo, let's add it to Hacktoberfest please.
Do assign it to me. I'll work on it. 😊
